### ISSUE TITLE
Historical Hackathons "select Year" dropdown only shows 2021 (NO LOGGIN)

### ISSUE THREAD

**Issue by jediMINDick** [Matt8728/hackathon_grader#75]
Issue:

When on the "Historical Hackathons" tab, page displays several past hackathons, but the "Select a Cohort Year" dropdown menu selector ONLY shows "2021"

Steps to reproduce:

- Main page
- Don't Log In 
- Select "Historical Hackathons" in the nav bar
- Click on "Select a Cohort Year"

**Comment by Matt8728** [comment]
This has been fixed. Needed to adjust the code on line 23. 



 `let years = [];
      let currentYear = "";
      for (let i = 0; i < res.data.length; i++) {
        // let year = new Date(res.data[i].year).getFullYear();
        let year = res.data[i].year;
        if (year != currentYear) {
          currentYear = year;
          years.push(currentYear);
        }
      }`
