### ISSUE TITLE
Unable to go back in the hackathon creation process

### ISSUE THREAD

**Issue by zyzzyxis** [Matt8728/hackathon_grader#76]
as a logged in person, I am able to create a hackathon, add objectives, and teams. however, if I navigate away from that process at any point the hackathon, objectives, and teams do not save and I am unable to get back to fix or update those items. 

this also happens if I mess up at any point in the process, if I mess up making a team and it throws and error, it gets rid of the hackathon and objectives and I'm unable to go back to add teams to it.

**Comment by Matt8728** [comment]
fixed
