### ISSUE TITLE
points get messed up if you delete objectives

### ISSUE THREAD

**Issue by ethanmcneal** [Matt8728/hackathon_grader#80]
![Screen Shot 2021-04-23 at 12 36 21 PM](https://user-images.githubusercontent.com/79327938/115915883-35ecdb80-a431-11eb-8d40-7c3194d47d2b.png)
![Screen Shot 2021-04-23 at 12 40 40 PM](https://user-images.githubusercontent.com/79327938/115915885-36857200-a431-11eb-84d4-8e0fddddd07f.png)

If you delete objectives when creating them, their points are still included in the total when you get to grading, and sometimes full time and part time point totals become equal, even if they shouldn't be

**Comment by maxmanayan** [comment]
Thanks... found bug in code and fixed -- currently testing fix

**Comment by Matt8728** [comment]
fixed
