### ISSUE TITLE
Nav Not Working in "Create Teams"

### ISSUE THREAD

**Issue by jediMINDick** [Matt8728/hackathon_grader#83]
issue:
When on "Create Teams" page, the upper URL-style navigation ONLY works for "/Objectives", NOT FOR "Hackathon/"
When you click "Hackathon", nothing happens

steps to reproduce:

- log in 
- navigate to "Create Teams" tab
- attempt to click "Hackathon" on upper left modal 
- witness NOTHING

**Comment by maxmanayan** [comment]
solved
thanks!
